#!/usr/bin/env sh
set -eu

if [ -d .git ]; then
  echo "Refusing to initialize: .git already exists" >&2
  exit 1
fi

tmp="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp"
}
trap cleanup EXIT

pnpm dlx sv create "$tmp" --template minimal --types ts --no-add-ons --install pnpm
cat << EOF
.direnv/
result
result-*
EOF >> "$tmp/.gitignore"
cp -a "$tmp"/. .

pnpm i -D prettier prettier-plugin-svelte


rm -- "$0"
git init
git add .
git commit -m "Initial commit"
